apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: istio
  tag: 1.9.4
  values:
    global:
      proxy:
        autoInject: enabled
      useMCP: false
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      label:
        istio: istio-ingressgateway
      k8s:
        service:
          type: LoadBalancer
          ports:
          - name: status-port
            port: 15021
            protocol: TCP
            targetPort: 15021
          - name: http2
            port: 80
            protocol: TCP
            targetPort: 8080
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8443
          - name: tcp-istiod
            port: 15012
            protocol: TCP
            targetPort: 15012
          - name: tls
            port: 15443
            protocol: TCP
            targetPort: 15443
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
    - name: knative-ingressgateway
      enabled: true
      label:
        istio: knative-ingressgateway
      k8s:
        service:
          type: ClusterIP
          ports:
          - name: status-port
            port: 15021
            protocol: TCP
            targetPort: 15021
          - name: http2
            port: 80
            protocol: TCP
            targetPort: 8080
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8443
          - name: tcp-istiod
            port: 15012
            protocol: TCP
            targetPort: 15012
          - name: tls
            port: 15443
            protocol: TCP
            targetPort: 15443
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
    - name: knative-localgateway
      enabled: true
      label:
        istio: knative-localgateway
      k8s:
        service:
          type: ClusterIP
          ports:
          - name: status-port
            port: 15021
            protocol: TCP
            targetPort: 15021
          - name: http2
            port: 8081
            protocol: TCP
            targetPort: 8080
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8443
          - name: tcp-istiod
            port: 15012
            protocol: TCP
            targetPort: 15012
          - name: tls
            port: 15443
            protocol: TCP
            targetPort: 15443
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
