apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httdrink
  namespace: istio-system
spec:
  hosts:
  - httdrink.akg.xyz
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - route:
    - destination:
        host: knative-localgateway.istio-system.svc.cluster.local
        port:
          number: 8081
      headers:
        request:
          set:
            Host: httdrink.default.svc.cluster.local
