apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-cert
  namespace: istio-system
spec:
  # Name of a secret that will be automagically created and used to store the cert
  secretName: letsencrypt-cert
  dnsNames:
  - "akg.xyz"
  - "*.akg.xyz"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
