# https://github.com/aevea/action-kaniko
name: Kaniko build
on: 
  push:
  workflow_dispatch:
jobs:
  akg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: bazhova/akg
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          path: ./pkg/akg
          cache: true
          cache_registry: bazhova/akg
          tag_with_latest: true
  httdrink:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: bazhova/httdrink
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          path: ./pkg/httdrink
          cache: true
          cache_registry: bazhova/httdrink
          tag_with_latest: true
  blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: bazhova/blog
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          path: ./pkg/blog
          cache: true
          cache_registry: bazhova/blog
          tag_with_latest: true
